remove fix ACR and APPservice

diff --git a/azure-pipelines-pr-close.yml b/azure-pipelines-pr-close.yml
--- a/azure-pipelines-pr-close.yml
+++ b/azure-pipelines-pr-close.yml
@@ -192,11 +192,11 @@ stages:
           az resource list --resource-group $(AZURE_RESOURCE_GROUP) --output table
     
     - task: AzureCLI@2
-      displayName: 'REMOVE ALL IF A/B are OFF'
+      displayName: 'REMOVE ACR for Variant1'
       condition: >
-        and(
+        or(
           eq(variables['createEnvironmentFound'], 'false'),
-          eq(variables['createEnvironmentBFound'], 'false')
+          eq('${{ parameters.WebhookPRtest.action }}', 'closed')
         )
       inputs:
         azureSubscription: 'radek-padrta-vs-msp'
@@ -209,12 +209,66 @@ stages:
           if az acr show --name $(ACR_NAME) --resource-group $(AZURE_RESOURCE_GROUP) &>/dev/null; then
             echo "Removing specific tag from ACR repository"
             az acr repository delete --name $(ACR_NAME) --image myapp:nextjsPOC-variant1 --yes || { echo "Failed to delete tag from ACR repository"; exit 1; }
+            echo "Tag removed successfully from ACR repository"
+          else
+            echo "Azure Container Registry does not exist, skipping tag removal"
+          fi
+
+          echo "All steps completed successfully"
+          
+          # Print out important information for debugging
+          echo "Resource Group: $(AZURE_RESOURCE_GROUP)"
+          
+          # List remaining resources in the resource group
+          echo "Remaining resources in the resource group:"
+          az resource list --resource-group $(AZURE_RESOURCE_GROUP) --output table
+    
+    - task: AzureCLI@2
+      displayName: 'REMOVE ACR for Variant2'
+      condition: >
+        or(
+          eq(variables['createEnvironmentBFound'], 'false'),
+          eq('${{ parameters.WebhookPRtest.action }}', 'closed')
+        )
+      inputs:
+        azureSubscription: 'radek-padrta-vs-msp'
+        scriptType: 'bash'
+        scriptLocation: 'inlineScript'
+        inlineScript: |
+          set -e  # Exit immediately if a command exits with a non-zero status
+         
+           echo "Checking if Azure Container Registry exists"
+          if az acr show --name $(ACR_NAME) --resource-group $(AZURE_RESOURCE_GROUP) &>/dev/null; then
+            echo "Removing specific tag from ACR repository"
             az acr repository delete --name $(ACR_NAME) --image myapp:nextjsPOC-variant2 --yes || { echo "Failed to delete tag from ACR repository"; exit 1; }
             echo "Tag removed successfully from ACR repository"
           else
             echo "Azure Container Registry does not exist, skipping tag removal"
           fi
 
+          echo "All steps completed successfully"
+          
+          # Print out important information for debugging
+          echo "Resource Group: $(AZURE_RESOURCE_GROUP)"
+          
+          # List remaining resources in the resource group
+          echo "Remaining resources in the resource group:"
+          az resource list --resource-group $(AZURE_RESOURCE_GROUP) --output table
+
+    - task: AzureCLI@2
+      displayName: 'REMOVE App Service'
+      condition: >
+        and(
+          eq(variables['createEnvironmentFound'], 'false'),
+          eq(variables['createEnvironmentBFound'], 'false'))
+        )
+      inputs:
+        azureSubscription: 'radek-padrta-vs-msp'
+        scriptType: 'bash'
+        scriptLocation: 'inlineScript'
+        inlineScript: |
+          set -e  # Exit immediately if a command exits with a non-zero status
+         
           echo "Checking if App Service Plan exists"
           if az appservice plan show --name $(APP_SERVICE_PLAN_NAME) --resource-group $(AZURE_RESOURCE_GROUP) &>/dev/null; then
             echo "Deleting App Service Plan"
